name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease
        # Note: Release build requires signing configuration
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apks
        path: |
          app/build/outputs/apk/debug/
          app/build/outputs/apk/release/
